=== 4equest/PyCTF-Framework/recipes/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "prepare-recipe-directory": {
            "type": "boolean"
        },
        "execution-chain": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "inrecipe-name": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string",
                        "enum": [
                            "module",
                            "recipe"
                        ]
                    },
                    "arguments": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "required": [
                    "name",
                    "inrecipe-name",
                    "type",
                    "arguments"
                ],
                "additionalProperties": false
            }
        },
        "output": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": [
        "name",
        "prepare-recipe-directory",
        "execution-chain",
        "output"
    ],
    "additionalProperties": false
}

=== 4equest/PyCTF-Framework/recipes/simple_flag_from_web.json
{
    "$schema": "./schema.json",
    "name": "simple_flag_from_web",
    "description": "Webサイトのディレクトリを探索し、フラグが含まれる可能性のあるファイルをダウンロードする",
    "prepare-recipe-directory": true,
    "execution-chain": [
        {
            "name": "curl",
            "type": "module",
            "inrecipe-name": "curl",
            "arguments": [
                "{input.0} > {recipe_dir}/curl.txt"
            ]
        },
        {
            "name": "grep",
            "type": "module",
            "inrecipe-name": "grep_flag",
            "arguments": [
                "{input.1}",
                "{recipe_dir}/curl.txt"
            ]
        }
    ],
    "output": [
        "{grep_flag.output.0}"
    ]
}

=== 4equest/PyCTF-Framework/recipes/ipinfo.json
{
    "$schema": "./schema.json",
    "name": "ipinfo",
    "prepare-recipe-directory": false,
    "execution-chain": [
        {
            "name": "curl",
            "type": "module",
            "inrecipe-name": "curl",
            "arguments": [
                "ipinfo.io/{input.0}"
            ]
        }
    ],
    "output": [
        "{curl.output}"
    ]
}

=== 4equest/PyCTF-Framework/recipes/analyze_pcap.json
{
    "$schema": "./schema.json",
    "name": "analyze_pcap",
    "description": "pcapファイルを分析し、フラグを探す",
    "prepare-recipe-directory": true,
    "execution-chain": [
        {
            "name": "tshark",
            "type": "module",
            "inrecipe-name": "http_packets",
            "arguments": [
                "-r",
                "{input.0}",
                "-Y",
                "http",
                "-T",
                "fields",
                "-e",
                "http.request_uri"
            ]
        },
        {
            "name": "extract_urls",
            "type": "module",
            "inrecipe-name": "extracted_urls",
            "arguments": [
                "{http_packets.output.0} | tee -a {recipe_dir}/extracted_urls.txt"
            ]
        },
        {
            "name": "download",
            "type": "module",
            "inrecipe-name": "downloaded_files",
            "arguments": [
                "{recipe_dir}/extracted_urls.txt",
                "{recipe_dir}"
            ]
        },
        {
            "name": "grep",
            "type": "module",
            "inrecipe-name": "grep_flag",
            "arguments": [
                "{input.1}",
                "{downloaded_files.output.0}"
            ]
        }
    ],
    "output": [
        "{http_packets.output.0}",
        "{extracted_urls.output.0}",
        "{grep_flag.output.0}"
    ]
}

=== 4equest/PyCTF-Framework/recipes/analyze_elf.json
{
    "$schema": "./schema.json",
    "name": "analyze_elf",
    "description": "ELFファイルを分析し、フラグを探す",
    "prepare-recipe-directory": true,
    "execution-chain": [
        {
            "name": "strings",
            "type": "module",
            "inrecipe-name": "strings_result",
            "arguments": [
                "{input.0} | tee -a {recipe_dir}/strings_result.txt"
            ]
        },
        {
            "name": "objdump",
            "type": "module",
            "inrecipe-name": "objdump_result",
            "arguments": [
                "{input.0} | tee -a {recipe_dir}/objdump_result.txt"
            ]
        },
        {
            "name": "grep",
            "type": "module",
            "inrecipe-name": "grep_flag_from_strings",
            "arguments": [
                "{input.1}",
                "{recipe_dir}/strings_result.txt"
            ]
        },
        {
            "name": "grep",
            "type": "module",
            "inrecipe-name": "grep_flag_from_objdump",
            "arguments": [
                "{input.1}",
                "{recipe_dir}/objdump_result.txt"
            ]
        }
    ],
    "output": [
        "{strings_result.output.0}",
        "{objdump_result.output.0}",
        "{grep_flag_from_strings.output.0}",
        "{grep_flag_from_objdump.output.0}"
    ]
}

=== 4equest/PyCTF-Framework/recipes/forensics_1.json
{
    "$schema": "./schema.json",
    "name": "forensics_1",
    "description": "Forensic analysis",
    "prepare-recipe-directory": true,
    "execution-chain": [
        {
            "name": "exiftool",
            "type": "module",
            "inrecipe-name": "exiftool_result",
            "arguments": [
                "{input.0} > {recipe_dir}/exiftool_result.txt"
            ]
        },
        {
            "name": "strings",
            "type": "module",
            "inrecipe-name": "strings_result",
            "arguments": [
                "{input.0} > {recipe_dir}/strings_result.txt"
            ]
        },
        {
            "name": "grep",
            "type": "module",
            "inrecipe-name": "grep_flag_from_exiftool",
            "arguments": [
                "{input.1}",
                "{recipe_dir}/exiftool_result.txt"
            ]
        },
        {
            "name": "grep",
            "type": "module",
            "inrecipe-name": "grep_flag_from_strings",
            "arguments": [
                "{input.1}",
                "{recipe_dir}/strings_result.txt"
            ]
        }
    ],
    "output": [
        "{grep_flag_from_exiftool.output.0}",
        "{grep_flag_from_strings.output.0}"
    ]
}

=== 4equest/PyCTF-Framework/recipes/extract_file_from_firmware.json
{
    "$schema": "./schema.json",
    "name": "extract_file_from_firmware",
    "description": "ファームウェアイメージからファイルを抽出する",
    "prepare-recipe-directory": true,
    "execution-chain": [
        {
            "name": "binwalk",
            "type": "module",
            "inrecipe-name": "binwalk_result",
            "arguments": [
                "{input.0}"
            ]
        },
        {
            "name": "extract_files",
            "type": "module",
            "inrecipe-name": "extracted_files",
            "arguments": [
                "{input.0}",
                "{recipe_dir}"
            ]
        }
    ],
    "output": [
        "{binwalk_result.output.0}",
        "{extracted_files.output.0}"
    ]
}
