=== 4equest/PyCTF-Framework/modules/json/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "type": {
            "type": "string",
            "enum": [
                "built-in",
                "external"
            ]
        },
        "name": {
            "type": "string"
        },
        "method": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "execution": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "environment": {
                    "type": "object",
                    "properties": {
                        "type": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "type"
                    ],
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "prepare-module-directory": {
            "type": "boolean",
            "additionalProperties": false
        },
        "data": {
            "type": "object",
            "properties": {
                "input": {
                    "type": "object",
                    "properties": {
                        "type": {
                            "type": "string",
                            "enum": [
                                "file",
                                "json"
                            ]
                        },
                        "path": {
                            "type": "string"
                        }
                    },
                    "additionalProperties": false
                },
                "output": {
                    "type": "object",
                    "properties": {
                        "type": {
                            "type": "string",
                            "enum": [
                                "file",
                                "json"
                            ]
                        },
                        "path": {
                            "type": "string"
                        }
                    },
                    "additionalProperties": false
                }
            },
            "required": [
                "input",
                "output"
            ],
            "additionalProperties": false
        }
    },
    "required": [
        "type",
        "name",
        "execution",
        "data"
    ],
    "additionalProperties": false,
    "allOf": [
        {
            "if": {
                "properties": {
                    "module": {
                        "properties": {
                            "type": {
                                "const": "built-in"
                            }
                        }
                    }
                }
            },
            "then": {
                "properties": {
                    "module": {
                        "required": [
                            "method"
                        ]
                    }
                }
            }
        },
        {
            "if": {
                "properties": {
                    "module": {
                        "properties": {
                            "type": {
                                "const": "external"
                            }
                        }
                    }
                }
            },
            "then": {
                "required": [
                    "execution"
                ]
            }
        }
    ]
}

=== 4equest/PyCTF-Framework/modules/json/grep.json
{
    "$schema": "./schema.json",
    "type": "external",
    "name": "grep",
    "description": "Search for patterns in input text.",
    "execution": {
        "command": [
            "grep",
            "{input.0}",
            "{input.1}"
        ]
    },
    "prepare-module-directory": false,
    "data": {
        "input": {
            "type": "json"
        },
        "output": {
            "type": "json"
        }
    }
}

=== 4equest/PyCTF-Framework/modules/json/file.json
{
    "$schema": "./schema.json",
    "type": "external",
    "name": "file",
    "description": "Get file information using the 'file' command.",
    "execution": {
        "command": [
            "file",
            "{input.0}"
        ]
    },
    "prepare-module-directory": false,
    "data": {
        "input": {
            "type": "json"
        },
        "output": {
            "type": "json"
        }
    }
}

=== 4equest/PyCTF-Framework/modules/json/extract_urls.json
{
    "$schema": "./schema.json",
    "type": "external",
    "name": "extract_urls",
    "description": "テキストからURLを抽出する",
    "execution": {
        "command": [
            "python3",
            "{cwd}/modules/extract_urls/extract_urls.py",
            "{input.0}"
        ]
    },
    "prepare-module-directory": false,
    "data": {
        "input": {
            "type": "json"
        },
        "output": {
            "type": "json"
        }
    }
}

=== 4equest/PyCTF-Framework/modules/json/binwalk.json
{
    "$schema": "./schema.json",
    "type": "external",
    "name": "binwalk",
    "description": "Analyze firmware images for embedded files and file systems.",
    "execution": {
        "command": [
            "binwalk",
            "{input.0}"
        ]
    },
    "prepare-module-directory": false,
    "data": {
        "input": {
            "type": "json"
        },
        "output": {
            "type": "json"
        }
    }
}

=== 4equest/PyCTF-Framework/modules/json/ipinfo.json
{
    "$schema": "./schema.json",
    "type": "external",
    "name": "ipinfo",
    "description": "Get IP information from ipinfo.io",
    "execution": {
        "command": [
            "curl",
            "ipinfo.io/{input.0}"
        ]
    },
    "prepare-module-directory": true,
    "data": {
        "input": {
            "type": "json"
        },
        "output": {
            "type": "json"
        }
    }
}

=== 4equest/PyCTF-Framework/modules/json/download.json
{
    "$schema": "./schema.json",
    "type": "external",
    "name": "download",
    "description": "URLからファイルをダウンロードする",
    "execution": {
        "command": [
            "wget",
            "-P {input.1}",
            "-i {input.0}"
        ]
    },
    "prepare-module-directory": false,
    "data": {
        "input": {
            "type": "json"
        },
        "output": {
            "type": "json"
        }
    }
}

=== 4equest/PyCTF-Framework/modules/json/nmap.json
{
    "$schema": "./schema.json",
    "type": "external",
    "name": "nmap",
    "description": "Perform port scanning using Nmap.",
    "execution": {
        "command": [
            "nmap",
            "{input.0}"
        ]
    },
    "prepare-module-directory": false,
    "data": {
        "input": {
            "type": "json"
        },
        "output": {
            "type": "json"
        }
    }
}
