=== 4equest/PyCTF-Framework/modules/json/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "type": {
            "type": "string",
            "enum": [
                "built-in",
                "external"
            ]
        },
        "name": {
            "type": "string"
        },
        "method": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "execution": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "environment": {
                    "type": "object",
                    "properties": {
                        "type": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "type"
                    ],
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "prepare-module-directory": {
            "type": "boolean",
            "additionalProperties": false
        },
        "data": {
            "type": "object",
            "properties": {
                "input": {
                    "type": "object",
                    "properties": {
                        "type": {
                            "type": "string",
                            "enum": [
                                "file",
                                "json"
                            ]
                        },
                        "path": {
                            "type": "string"
                        }
                    },
                    "additionalProperties": false
                },
                "output": {
                    "type": "object",
                    "properties": {
                        "type": {
                            "type": "string",
                            "enum": [
                                "file",
                                "json"
                            ]
                        },
                        "path": {
                            "type": "string"
                        }
                    },
                    "additionalProperties": false
                }
            },
            "required": [
                "input",
                "output"
            ],
            "additionalProperties": false
        }
    },
    "required": [
        "type",
        "name",
        "execution",
        "data"
    ],
    "additionalProperties": false,
    "allOf": [
        {
            "if": {
                "properties": {
                    "module": {
                        "properties": {
                            "type": {
                                "const": "built-in"
                            }
                        }
                    }
                }
            },
            "then": {
                "properties": {
                    "module": {
                        "required": [
                            "method"
                        ]
                    }
                }
            }
        },
        {
            "if": {
                "properties": {
                    "module": {
                        "properties": {
                            "type": {
                                "const": "external"
                            }
                        }
                    }
                }
            },
            "then": {
                "required": [
                    "execution"
                ]
            }
        }
    ]
}

=== 4equest/PyCTF-Framework/modules/json/curl.json
{
    "$schema": "./schema.json",
    "type": "external",
    "name": "curl",
    "description": "curl",
    "execution": {
        "command": [
            "curl",
            "{input.0}"
        ]
    },
    "prepare-module-directory": false,
    "data": {
        "input": {
            "type": "json"
        },
        "output": {
            "type": "json"
        }
    }
}

=== 4equest/PyCTF-Framework/modules/json/objdump.json
{
    "$schema": "./schema.json",
    "type": "external",
    "name": "objdump",
    "description": "Display information from object files.",
    "execution": {
        "command": [
            "objdump",
            "-d",
            "{input.0}"
        ]
    },
    "prepare-module-directory": false,
    "data": {
        "input": {
            "type": "json"
        },
        "output": {
            "type": "json"
        }
    }
}

=== 4equest/PyCTF-Framework/modules/json/exiftool.json
{
    "$schema": "./schema.json",
    "type": "external",
    "name": "exiftool",
    "description": "Extract metadata from files using Exiftool.",
    "execution": {
        "command": [
            "exiftool",
            "{input.0}"
        ]
    },
    "prepare-module-directory": false,
    "data": {
        "input": {
            "type": "json"
        },
        "output": {
            "type": "json"
        }
    }
}

=== 4equest/PyCTF-Framework/modules/json/b64decode.json
{
    "$schema": "./schema.json",
    "type": "external",
    "name": "base64decode",
    "description": "Decode Base64 encoded text.",
    "execution": {
        "command": [
            "echo",
            "{input.0}",
            "|",
            "base64",
            "-d"
        ]
    },
    "prepare-module-directory": false,
    "data": {
        "input": {
            "type": "json"
        },
        "output": {
            "type": "json"
        }
    }
}

=== 4equest/PyCTF-Framework/modules/json/hashcalc.json
{
    "$schema": "./schema.json",
    "type": "external",
    "name": "hashcalc",
    "description": "Calculate MD5, SHA1, SHA256 hashes of a file or text.",
    "execution": {
        "command": [
            "python3",
            "{cwd}/modules/hashcalc/hashcalc.py",
            "{input.0}",
            "{input.1}"
        ]
    },
    "prepare-module-directory": false,
    "data": {
        "input": {
            "type": "json"
        },
        "output": {
            "type": "json"
        }
    }
}

=== 4equest/PyCTF-Framework/modules/json/extract_files.json
{
    "$schema": "./schema.json",
    "type": "external",
    "name": "extract_files",
    "description": "binwalkで解析したファイルシステムを抽出する",
    "execution": {
        "command": [
            "binwalk",
            "-e",
            "{input.0}",
            "-C",
            "{input.1}"
        ]
    },
    "prepare-module-directory": false,
    "data": {
        "input": {
            "type": "json"
        },
        "output": {
            "type": "json"
        }
    }
}

=== 4equest/PyCTF-Framework/modules/json/tshark.json
{
    "$schema": "./schema.json",
    "type": "external",
    "name": "tshark",
    "description": "pcapファイルを解析する",
    "execution": {
        "command": [
            "tshark",
            "{input.0}"
        ]
    },
    "prepare-module-directory": false,
    "data": {
        "input": {
            "type": "json"
        },
        "output": {
            "type": "json"
        }
    }
}

=== 4equest/PyCTF-Framework/modules/json/b64encode.json
{
    "$schema": "./schema.json",
    "type": "external",
    "name": "base64encode",
    "description": "Encode text to Base64.",
    "execution": {
        "command": [
            "echo",
            "{input.0}",
            "|",
            "base64"
        ]
    },
    "prepare-module-directory": false,
    "data": {
        "input": {
            "type": "json"
        },
        "output": {
            "type": "json"
        }
    }
}
